---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-web-mywebsite-com-v1-webpage
  failurePolicy: Fail
  name: mwebpage-v1.kb.io
  rules:
  - apiGroups:
    - web.mywebsite.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - webpages
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-web-mywebsite-com-v1-webpage
  failurePolicy: Fail
  name: vwebpage-v1.kb.io
  rules:
  - apiGroups:
    - web.mywebsite.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - webpages
  sideEffects: None
