# This rule is not used by the project my-website itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to web.mywebsite.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: my-website
    app.kubernetes.io/managed-by: kustomize
  name: webpage-viewer-role
rules:
- apiGroups:
  - web.mywebsite.com
  resources:
  - webpages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - web.mywebsite.com
  resources:
  - webpages/status
  verbs:
  - get
